# Generated by Django 3.2.6 on 2021-11-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.area')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('lvl_estudio', models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico'), ('Universitario', 'Universitario'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cedula', models.CharField(max_length=12)),
                ('genero', models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], max_length=20, null=True)),
                ('sangre', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=20, null=True)),
                ('turno_trabajo', models.CharField(max_length=12)),
                ('telefono_fijo', models.PositiveIntegerField(blank=True, null=True)),
                ('celular', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True)),
                ('municipio', models.CharField(blank=True, max_length=30, null=True)),
                ('estrato', models.PositiveSmallIntegerField(blank=True, help_text='De 1 a 6', null=True)),
                ('etnias', models.CharField(blank=True, choices=[('Blanco', 'Blanco'), ('Mestizo', 'Mestizo'), ('Afrocolombiano', 'Afrocolombiano'), ('Mulato', 'Mulato'), ('Indígena', 'Indígena')], max_length=20, null=True)),
                ('civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Separado', 'Separado'), ('Unión Libre', 'Unión Libre'), ('Viudo', 'Viudo')], max_length=20, null=True)),
                ('hijos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=30, null=True)),
                ('enfermedad', models.CharField(blank=True, help_text='Si no sufre ninguna enfermedad, dejar campo en blanco', max_length=30, null=True)),
                ('induccion', models.BooleanField(blank=True, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=30, null=True)),
                ('vacuna', models.BooleanField(blank=True, null=True)),
                ('carnet', models.FileField(blank=True, null=True, upload_to='')),
                ('estado_actividad', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='SeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(max_length=20)),
                ('afp', models.CharField(max_length=20)),
                ('ccf', models.CharField(max_length=20)),
                ('arl', models.CharField(max_length=20)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('celular', models.PositiveIntegerField(blank=True, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto_emergencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
            ],
        ),
    ]
