# Generated by Django 3.2.6 on 2021-11-19 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='id',
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='contacto_emergencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Empleados.empleados'),
        ),
    ]
