# Generated by Django 3.2.6 on 2021-11-23 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0002_auto_20211118_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=11)),
                ('longitud', models.CharField(max_length=25)),
                ('latitud', models.CharField(max_length=25)),
                ('actividad_economica', models.CharField(max_length=30)),
                ('nivel_riesgo', models.CharField(max_length=30)),
                ('cantidad_trabajadores', models.PositiveBigIntegerField()),
                ('naturaleza_juridica', models.CharField(max_length=30)),
                ('telefono1', models.BigIntegerField()),
                ('telefono2', models.BigIntegerField(blank=True, null=True)),
                ('telefono3', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('pagina_web', models.URLField()),
                ('tipo_empresa', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposdeDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descripcion', models.TextField(max_length=50)),
                ('firma', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(max_length=300)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentacion.tiposdedocumento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='SSGST/documentos')),
                ('fecha_vencimiento', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(max_length=300)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentacion.tiposdedocumento')),
            ],
        ),
    ]
